import { NgModule } from '@angular/core';

import { MatButtonModule,
         MatCardModule,
         MatMenuModule,
         MatToolbarModule, 
         MatIconModule,
         MatInputModule,
         MatDatepickerModule,
         MatNativeDateModule,
         MatProgressSpinnerModule,
         MatTableModule,
         MatExpansionModule,
         MatSelectModule,
         MatSnackBarModule,
         MatTooltipModule,
         MatChipsModule,
         MatListModule,
         MatSidenavModule,
         MatTabsModule,
         MatDialog,
         MatDialogRef,
         MAT_DIALOG_DATA,
         MatDialogModule,
         MatProgressBarModule } from '@angular/material';

@NgModule({
  imports: [
        MatButtonModule,
        MatCardModule,
        MatMenuModule,
        MatToolbarModule,
        MatIconModule,
        MatInputModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatProgressSpinnerModule,
        MatTableModule,
        MatExpansionModule,
        MatSelectModule,
        MatSnackBarModule,
        MatTooltipModule,
        MatChipsModule,
        MatListModule,
        MatSidenavModule,
        MatTabsModule,
        MatProgressBarModule,
        MatDialogModule
  ],
  exports: [
        MatButtonModule,
        MatCardModule,
        MatMenuModule,
        MatToolbarModule,
        MatIconModule,
        MatInputModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatProgressSpinnerModule,
        MatTableModule,
        MatExpansionModule,
        MatSelectModule,
        MatSnackBarModule,
        MatTooltipModule,
        MatChipsModule,
        MatListModule,
        MatSidenavModule,
        MatTabsModule,
        MatProgressBarModule,
        MatDialogModule
  ]
})
export class MaterialModule {}